import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import { Toaster } from "sonner";

import "./globals.css";

import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer";

const font_used = Roboto_Condensed({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Toaster richColors position="top-center" />
      <body className={font_used.className}>
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
